version: '3.3'

volumes:
  wsgi_app:

services:
  web:
    build: .
    restart: always
    command: gunicorn app:app --bind 0.0.0.0:8000 --timeout 90
    ports:
      - "8000:8000"
    volumes:
      - wsgi_app:/code
